
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// API Base URL - uses environment variable in production, relative path in dev
const API_URL = import.meta.env.VITE_API_URL || '/api/v1';

// Express AI Branding Colors - Blue/Black Theme (Formal)
const COLORS = {
    blue: [37, 99, 235],       // Blue-600 #2563eb (for "Express")
    green: [22, 163, 74],      // Green-600 #16a34a (for "AI" and table headers)
    black: [17, 24, 39],       // Gray-900 (for section headers)
    secondary: [31, 41, 55],   // Gray-800
    text: [55, 65, 81],        // Gray-700
    lightBg: [240, 249, 255],  // Blue-50 (KPI boxes)
    lightGreen: [240, 253, 244] // Green-50
};

// Helper to load image as base64 (using fetch to support auth headers)
const loadImageAsBase64 = async (url, token = null) => {
    try {
        const headers = {};
        // Add auth token if provided and URL is local/proxy
        if (token && (url.startsWith('/') || url.includes('/api/v1'))) {
            headers['Authorization'] = `Bearer ${token}`;
        }

        const response = await fetch(url, { headers });
        if (!response.ok) {
            console.warn(`Image fetch failed: ${response.status} for ${url}`);
            throw new Error(`HTTP ${response.status}`);
        }

        const blob = await response.blob();
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    } catch (e) {
        console.error('loadImageAsBase64 failed:', url, e);
        throw e;
    }
};

export const generateReport = async (projectData, getToken = null) => {
    // Get fresh token if provided
    const token = getToken ? await getToken() : null;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    let currentY = 0;

    // Try to load logo
    let logoData = null;
    try {
        // Use standard path
        logoData = await loadImageAsBase64('/logos/express-ai-logo.png', token);
    } catch (e) {
        console.warn('Could not load logo, using text fallback');
    }

    // Helper: Add Logo
    const addLogo = () => {
        if (logoData) {
            // Use the actual PNG logo
            doc.addImage(logoData, 'PNG', 15, 12, 25, 25);
        } else {
            // Fallback: Draw diamond shape
            doc.setFillColor(...COLORS.blue); // Changed from COLORS.green to COLORS.blue (assuming 'primary' refers to the main brand blue)
            doc.triangle(20, 25, 30, 25, 25, 15, 'F');
            doc.triangle(20, 25, 30, 25, 25, 35, 'F');
        }

        // "Express" in Blue
        doc.setTextColor(...COLORS.blue);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('Express', 45, 24);

        // "AI" in Black (Fixed as per request)
        doc.setTextColor(...COLORS.black);
        doc.text('AI', 45 + doc.getTextWidth('Express') + 3, 24);

        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text('Expert Platform for Road Evaluation and Smart Surveillance', 45, 30);
    };

    // Helper: Footer with Page Number
    const addFooter = (pageNumber) => {
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${pageNumber} - Generated by Express AI System`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    };

    // --- 1. COVER PAGE ---
    addLogo();

    currentY = 100;
    doc.setFontSize(36);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text('ROAD QUALITY', pageWidth / 2, currentY, { align: 'center' });
    currentY += 15;
    doc.text('ASSESSMENT REPORT', pageWidth / 2, currentY, { align: 'center' });

    currentY += 40;
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.text);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date of Survey: ${new Date().toLocaleDateString()}`, pageWidth / 2, currentY, { align: 'center' });

    currentY += 10;
    doc.text(`Report Generated: ${new Date().toLocaleTimeString()}`, pageWidth / 2, currentY, { align: 'center' });

    currentY += 50;
    doc.setFontSize(12);
    doc.text('Prepared for:', pageWidth / 2, currentY, { align: 'center' });
    currentY += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Department of Science and Technology -', pageWidth / 2, currentY, { align: 'center' });
    currentY += 6;
    doc.text('National Research Council of the Philippines (DOST-NRCP)', pageWidth / 2, currentY, { align: 'center' });

    addFooter(1);
    doc.addPage();

    // --- 2. EXECUTIVE SUMMARY ---
    let pageNum = 2;
    currentY = 20;

    doc.setFontSize(18);
    doc.setTextColor(...COLORS.black); // Black header
    doc.setFont('helvetica', 'bold');
    doc.text('Executive Summary', 20, currentY);

    currentY += 12;
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.text);
    doc.setFont('helvetica', 'normal');
    doc.text('This report presents a comprehensive analysis of the road pavement condition based on data collected using the Express AI system. The survey evaluates International Roughness Index (IRI), identifies anomalies (potholes), and provides actionable maintenance recommendations.', 20, currentY, { maxWidth: 170 });

    currentY += 30;

    // KPI Grid
    const kpiY = currentY;
    const boxW = 80;
    const boxH = 25;

    // Total Distance
    doc.setFillColor(...COLORS.lightBg);
    doc.rect(20, kpiY, boxW, boxH, 'F');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.secondary);
    doc.text('Total Distance Surveyed', 25, kpiY + 8);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`${(projectData.summary.totalDistance / 1000).toFixed(2)} km`, 25, kpiY + 18);

    // Avg IRI
    doc.setFillColor(...COLORS.lightBg);
    doc.rect(110, kpiY, boxW, boxH, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Average IRI', 115, kpiY + 8);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`${projectData.summary.avgIri.toFixed(2)} m/km`, 115, kpiY + 18);

    currentY += 35;

    // Potholes
    doc.setFillColor(...COLORS.lightBg);
    doc.rect(20, currentY, boxW, boxH, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Total Anomalies Detected', 25, currentY + 8);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.secondary);
    doc.text(`${projectData.summary.totalPotholes}`, 25, currentY + 18);

    // Critical Issues
    doc.setFillColor(...COLORS.lightBg);
    doc.rect(110, currentY, boxW, boxH, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Critical Sections ("Bad")', 115, currentY + 8);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // Red
    doc.text(`${projectData.summary.criticalSegments}`, 115, currentY + 18);

    currentY += 40;
    addFooter(pageNum);

    // --- 3. SURVEY METADATA ---
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black); // Black header
    doc.setFont('helvetica', 'bold');
    doc.text('Survey Metadata', 20, currentY);
    currentY += 10;

    autoTable(doc, {
        startY: currentY,
        head: [['Parameter', 'Value']],
        body: [
            ['System Version', 'Express AI v1.0'],
            ['Data Collection Date', new Date().toLocaleDateString()],
            ['Total Files Processed', projectData.files.length],
            ['IRI Segment/Cutoff', '25m / 10.0 Hz (Configurable)'],
        ],
        theme: 'striped',
        headStyles: { fillColor: COLORS.green },
        styles: { fontSize: 10 }
    });

    currentY = doc.lastAutoTable.finalY + 20;

    // --- 4. IRI ANALYSIS ---
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black); // Black header
    doc.setFont('helvetica', 'bold');
    doc.text('IRI Analysis & Quality Assessment', 20, currentY);
    currentY += 10;

    const iriBody = projectData.files.map(f => [
        f.filename,
        f.stats.averageIri.toFixed(2),
        f.stats.quality.rating,
        f.stats.quality.description
    ]);

    autoTable(doc, {
        startY: currentY,
        head: [['Filename', 'Avg IRI (m/km)', 'Rating', 'Condition']],
        body: iriBody,
        theme: 'grid',
        headStyles: { fillColor: COLORS.green },
        columnStyles: {
            0: { cellWidth: 60 },
            2: { fontStyle: 'bold' }
        },
        didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 2) {
                const rating = data.cell.raw;
                if (rating === 'Good') data.cell.styles.textColor = [22, 163, 74];
                if (rating === 'Fair') data.cell.styles.textColor = [234, 179, 8];
                if (rating === 'Poor') data.cell.styles.textColor = [234, 88, 12];
                if (rating === 'Bad') data.cell.styles.textColor = [220, 38, 38];
            }
        }
    });

    // --- 5. POTHOLE INVENTORY ---
    doc.addPage();
    pageNum++;
    currentY = 20;
    addFooter(pageNum);

    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black); // Black header
    doc.setFont('helvetica', 'bold');
    doc.text('Pothole Inventory', 20, currentY);
    currentY += 10;

    if (projectData.potholes && projectData.potholes.length > 0) {
        // Top 15 for table
        const topPotholes = projectData.potholes
            .sort((a, b) => b.confidence - a.confidence)
            .slice(0, 15)
            .map((p, idx) => [
                idx + 1,
                (p.confidence * 100).toFixed(1) + '%',
                `${p.lat?.toFixed(6) || 'N/A'}, ${p.lon?.toFixed(6) || 'N/A'}`,
                new Date(p.upload_date || Date.now()).toLocaleDateString()
            ]);

        doc.setFontSize(10);
        doc.setTextColor(...COLORS.text);
        doc.text(`Total Detected: ${projectData.potholes.length}. Showing top ${topPotholes.length} highest confidence detections.`, 20, currentY);
        currentY += 5;

        autoTable(doc, {
            startY: currentY,
            head: [['ID', 'Confidence', 'Location (Lat, Lon)', 'Date']],
            body: topPotholes,
            theme: 'striped',
            headStyles: { fillColor: COLORS.green },
        });
        currentY = doc.lastAutoTable.finalY + 15;

        // --- POTHOLE IMAGE GRID (Top 10) ---
        // Check if we have enough space for the title, if not add page
        if (currentY + 20 > pageHeight - 30) {
            doc.addPage();
            pageNum++;
            addFooter(pageNum);
            currentY = 20;
        }

        doc.setFontSize(12);
        doc.setTextColor(...COLORS.black);
        doc.setFont('helvetica', 'bold');
        doc.text('High Confidence Detection Images', 20, currentY);
        currentY += 15; // Space below title

        // Get top 10 potholes with images
        const potholesWithImages = projectData.potholes
            .filter(p => p.image_url)
            .sort((a, b) => b.confidence - a.confidence)
            .slice(0, 10);

        if (potholesWithImages.length > 0) {
            // Grid config
            const imgWidth = 80;
            const imgHeight = 50;
            const colGap = 10;
            const rowGap = 20;
            const startX = 20;

            // Render loop
            for (let i = 0; i < potholesWithImages.length; i++) {
                const p = potholesWithImages[i];
                const col = i % 2; // 0 or 1

                // Calculate position
                const x = startX + (col * (imgWidth + colGap));

                // Check if we need a new page BEFORE drawing
                // If this is the START of a new row (col === 0), check if the row fits
                if (col === 0) {
                    if (currentY + imgHeight + 20 > pageHeight - 30) {
                        doc.addPage();
                        pageNum++;
                        addFooter(pageNum);
                        currentY = 20; // Reset Y to top for new page
                    }
                }

                const y = currentY; // Use current Y for this row

                try {
                    // Always route through the backend proxy so we never hit a stale
                    // presigned URL (they expire after 1-24h). The proxy re-fetches from
                    // R2 on every call, so the PDF always gets a fresh image.
                    //
                    // Priority:
                    //   1. storage_path  → /pothole/proxy?key=...  (fastest, most reliable)
                    //   2. image_path / imagePath filename → /pothole/image/:filename (DB lookup)
                    //   3. raw image_url  (last resort — may fail if presigned URL expired)

                    const filename = p.image_path || p.imagePath
                        || (p.image_url ? p.image_url.split('/').pop().split('?')[0] : null);

                    let imgUrl;
                    if (p.storage_path) {
                        // Best path: direct storage key proxy — always fresh, no expiry risk
                        imgUrl = `${API_URL}/pothole/proxy?key=${encodeURIComponent(p.storage_path)}`;
                    } else if (filename && !filename.startsWith('http') && !filename.startsWith('blob')) {
                        // Fallback: filename-based DB lookup proxy
                        imgUrl = `${API_URL}/pothole/image/${filename}`;
                    } else {
                        // Last resort: use the raw URL as-is (presigned URL may be expired)
                        imgUrl = p.image_url;
                    }

                    const imgData = await loadImageAsBase64(imgUrl, token);
                    doc.addImage(imgData, 'JPEG', x, y, imgWidth, imgHeight);
                } catch (e) {
                    console.warn("Failed to load image via proxy, falling back to original URL", e);
                    try {
                        // Fallback to original URL (external URLs usually don't need our token)
                        const imgData = await loadImageAsBase64(p.image_url);
                        doc.addImage(imgData, 'JPEG', x, y, imgWidth, imgHeight);
                    } catch (e2) {
                        // Draw placeholder box if image fails
                        doc.setDrawColor(200);
                        doc.rect(x, y, imgWidth, imgHeight);
                        doc.setFontSize(8);
                        doc.setTextColor(150);
                        doc.text('Image not available', x + 15, y + 25);
                    }
                }

                // Add ID label below image
                doc.setFontSize(9);
                doc.setTextColor(...COLORS.black);
                doc.text(`ID: ${i + 1} | Conf: ${(p.confidence * 100).toFixed(0)}%`, x, y + imgHeight + 5);

                // If this is the second column (col === 1), OR it's the last item, advance Y
                if (col === 1 || i === potholesWithImages.length - 1) {
                    currentY += (imgHeight + rowGap);
                }
            }
        } else {
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text('No pothole images available.', 20, currentY);
        }
    } else {
        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text('No potholes detected in the surveyed segments.', 20, currentY);
    }

    // --- 6. TRAFFIC ANALYTICS ---
    doc.addPage();
    pageNum++;
    currentY = 20;
    addFooter(pageNum);

    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text('Traffic Analytics', 20, currentY);
    currentY += 10;

    if (projectData.traffic && projectData.traffic.totalCount > 0) {
        doc.setFontSize(11);
        doc.setTextColor(...COLORS.text);
        doc.text(`Total Vehicles Detected: ${projectData.traffic.totalCount}`, 20, currentY);
        currentY += 10;

        const trafficBody = projectData.traffic.compositionData.map(v => [
            v.name,
            v.value,
            ((v.value / projectData.traffic.totalCount) * 100).toFixed(1) + '%'
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['Vehicle Type', 'Count', 'Percentage']],
            body: trafficBody,
            theme: 'striped',
            headStyles: { fillColor: COLORS.green },
        });
        currentY = doc.lastAutoTable.finalY + 20;
    } else {
        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text('No traffic data available for this survey.', 20, currentY);
        currentY += 20;
    }

    // --- 7. PAVEMENT TYPE ANALYSIS ---
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text('Pavement Type Distribution', 20, currentY);
    currentY += 10;

    if (projectData.pavement && projectData.pavement.totalSegments > 0) {
        doc.setFontSize(11);
        doc.setTextColor(...COLORS.text);
        doc.text(`Total Segments Analyzed: ${projectData.pavement.totalSegments}`, 20, currentY);
        currentY += 10;

        const pavementBody = projectData.pavement.pavementData.map(p => [
            p.name,
            p.value,
            ((p.value / projectData.pavement.totalSegments) * 100).toFixed(1) + '%'
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [['Pavement Type', 'Segments', 'Percentage']],
            body: pavementBody,
            theme: 'striped',
            headStyles: { fillColor: COLORS.green },
        });
        currentY = doc.lastAutoTable.finalY + 20;
    } else {
        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text('No pavement type data available for this survey.', 20, currentY);
        currentY += 20;
    }

    // --- 8. RECOMMENDATIONS ---
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations & Interpretation', 20, currentY);
    currentY += 10;

    const overallIRI = projectData.summary.avgIri;
    let recTitle = '';
    let recText = '';

    if (overallIRI <= 3) {
        recTitle = 'Condition: Good - Routine Maintenance';
        recText = 'The road network is in good condition. Continue with routine monitoring and preventive maintenance (sealing cracks) to extend service life.';
    } else if (overallIRI <= 5) {
        recTitle = 'Condition: Fair - Minor Rehabilitation';
        recText = 'Surface roughness is beginning to impact ride quality. Consider thin overlay or surface treatments in affected sections to restore smoothness.';
    } else if (overallIRI <= 7) {
        recTitle = 'Condition: Poor - Major Rehabilitation';
        recText = 'Significant deterioration detected. Structural capacity may be compromised. Prioritize resurfacing or mill-and-overlay for critical segments.';
    } else {
        recTitle = 'Condition: Bad - Reconstruction';
        recText = 'Severe distress indicates structural failure. Full reconstruction or major rehabilitation is recommended urgently to ensure safety.';
    }

    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...COLORS.blue);
    doc.rect(20, currentY, 170, 40);

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.secondary);
    doc.setFont('helvetica', 'bold');
    doc.text(recTitle, 25, currentY + 10);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(recText, 25, currentY + 20, { maxWidth: 160 });

    // --- 9. APPENDIX ---
    doc.addPage();
    pageNum++;
    addFooter(pageNum);
    currentY = 20;

    doc.setFontSize(14);
    doc.setTextColor(...COLORS.black);
    doc.setFont('helvetica', 'bold');
    doc.text('Appendix: Detailed Segment Analysis', 20, currentY);
    currentY += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Detailed breakdown of all processed segments.', 20, currentY);
    currentY += 10;

    // Collect ALL segments from ALL files
    const allSegments = [];
    projectData.files.forEach(f => {
        if (f.segments) {
            f.segments.forEach(seg => {
                allSegments.push({
                    file: f.filename,
                    distance: `${seg.distance_start?.toFixed(0) || 0}-${seg.distance_end?.toFixed(0) || 0}m`,
                    iri: seg.iri_value?.toFixed(2) || 'N/A',
                    rating: seg.iri_value <= 3 ? 'Good' : seg.iri_value <= 5 ? 'Fair' : seg.iri_value <= 7 ? 'Poor' : 'Bad',
                    location: `${seg.start_lat?.toFixed(5) || 'N/A'}, ${seg.start_lon?.toFixed(5) || 'N/A'}`
                });
            });
        }
    });

    autoTable(doc, {
        startY: currentY,
        head: [['File', 'Interval', 'IRI', 'Rating', 'Location']],
        body: allSegments.map(s => [s.file, s.distance, s.iri, s.rating, s.location]),
        theme: 'plain',
        headStyles: { fillColor: [200, 200, 200], textColor: 0 },
        styles: { fontSize: 8, cellPadding: 2 },
        columnStyles: {
            0: { cellWidth: 40 },
            4: { cellWidth: 50 },
            3: { fontStyle: 'bold' }
        },
        didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 3) {
                const rating = data.cell.raw;
                if (rating === 'Bad') data.cell.styles.textColor = [220, 38, 38];
                if (rating === 'Poor') data.cell.styles.textColor = [234, 88, 12];
            }
        }
    });

    // Save
    doc.save(`ExpressAI_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
